### ISSUE TITLE
No table to load on Safari browser [BUG] 

### ISSUE THREAD

**Issue by Bharath-Bandaru** [ng-web-apis/audio#14]
# 🐞 Bug report

After I implemented ng-web-apis I am not able to open application on safari.
On console it say "ReferenceError: Can't find variable: OscillatorNode".
Is there any solution that will work?

Thanks.

**Comment by waterplea** [comment]
Hi @Bharath-Bandaru . What version of Safari you see that issue in? Does OscillatorNode mode work in this demo for you?
https://ng-web-apis.github.io/audio/

**Comment by waterplea** [comment]
Hi again @Bharath-Bandaru. I discovered that polyfill is dropped by build optimizer. It was fixed in the latest release but I'm still seeing some issues with Safari so I will leave this issue open until I fix it all.

**Comment by waterplea** [comment]
Ok, I got it fixed. The issue was that in Safari prototype chain was wrong. This all should be fixed in v1.3.3, **don't forget to add  `@ng-web-apis/audio/polyfill` to your `polyfills.ts`**.
